apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kube-queue-job-class: "<%= spec.job_class %>"
    kube-queue-job-id: "<%= job.job_id %>"
    kube-queue-job-payload: '<%= payload %>'
  name: "<%= spec.job_name(job.job_id) %>"
  namespace: <%= spec.namespace %>
  labels:
    kube-queue-job: "true"
    kube-queue-worker-name: "<%= spec.worker_name %>"
    kube-queue-job-class: "<%= spec.job_class %>"
    kube-queue-job-id: "<%= job.job_id %>"
spec:
  template:
    metadata:
      annotations:
        kube-queue-job-class: "<%= spec.job_class %>"
        kube-queue-job-id: "<%= job.job_id %>"
        kube-queue-job-payload: '<%= payload %>'
      labels:
        kube-queue-job: "true"
        kube-queue-worker-name: "<%= spec.worker_name %>"
        kube-queue-job-class: "<%= spec.job_class %>"
        kube-queue-job-id: "<%= job.job_id %>"
<%- spec.job_labels.each do |key, value| %>
        <%= key %>: "<%= value %>"
<%- end %>
    spec:
      containers:
      - name: "<%= spec.container_name %>"
        image: "<%= spec.image %>"
        command: <%= spec.command %>
        env:
        - name: "KUBE_QUEUE_MESSAGE_PAYLOAD"
          value: '<%= payload %>'
<%- spec.env.each do |key, value| %>
        - name: "<%= key %>"
          value: "<%= value %>"
<%- end %>
<%- if spec.env_from_exists? %>
        envFrom:
  <%- spec.env_from_config_map.each do |name| %>
        - configMapRef:
            name: "<%= name %>"
  <%- end %>
  <%- spec.env_from_secret.each do |name| %>
        - secretRef:
            name: "<%= name %>"
  <%- end %>
<%- end %>
<%- if spec.resources_exists? %>
        resources:
  <%- if spec.cpu_limit || spec.memory_limit %>
          limits:
    <%- if spec.cpu_limit %>
            cpu: <%= spec.cpu_limit %>
    <%- end %>
    <%- if spec.memory_limit %>
            memory: <%= spec.memory_limit %>
    <%- end %>
  <%- end %>
  <%- if spec.cpu_request || spec.memory_request %>
          requests:
    <%- if spec.cpu_request %>
            cpu: <%= spec.cpu_request %>
    <%- end %>
    <%- if spec.memory_request %>
            memory: <%= spec.memory_request %>
    <%- end %>
  <%- end %>
<%- else %>
      resources: {}
<%- end %>
      restartPolicy: "<%= spec.restart_policy %>"
  backoffLimit: <%= spec.backoff_limit %>
  activeDeadlineSeconds: <%= spec.active_deadline_seconds %>
