apiVersion: batch/v1
kind: Job
metadata:
  name: "<%= worker_name %>-<%= id %>"
  namespace: <%= namespace %>
spec:
  template:
    metadata:
      labels:
<%- labels.each do |key, value| %>
        <%= key %>: "<%= value %>"
<%- end %>
    spec:
      containers:
      - name: "<%= container_name %>"
        image: "<%= image %>"
        command: <%= command %>
        env:
        - name: "KUBE_QUEUE_MESSAGE_PAYLOAD"
          value: '<%= payload %>'
      restartPolicy: "<%= restart_policy %>"
  backoffLimit: <%= backoff_limit %>
  activeDeadlineSeconds: <%= active_deadline_seconds %>
