require:
- rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - Gemfile
  - Rakefile
  - examples/**/*
  - kube_queue.gemspec
  - Guardfile
  - vendor/**/*
  DisplayCopNames: true

Gemspec/OrderedDependencies:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 128

Style/EmptyCaseCondition:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Style/ParallelAssignment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'spec/**/*.rb'
