sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.5
- 2.6.3
- ruby-head
branches:
  only:
  - master
before_install: gem install bundler -v 2.0.2
script:
- bundle exec rspec
gem_files:
- gemfiles/rails_5.1.gemfile
- gemfiles/rails_5.2.gemfile
- gemfiles/rails_6.0.gemfile
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
notifications:
  slack:
    secure: P996C+m/+CeH9RacgDyVWYY7jdOKR3/FA194GwXE+l5Yc51AtH0Us8EWhaizNUPmxIO9DI8wFrX+/RYTl0mV2dOAToj655yTNIQAPh+FFHbC3dpjwHejXP90cWstwdR/PBPsy71sMk476RQPl4jWzR+OOoCQdyEWPUlYnVhu+DR2Tt54ixcoZqb7Li/s5gQCY7RDXBlO/lNA4nvslHTUTtdlHYM9MnUFtvYa/aCQ16bvHk/HdzUKUiZ1mZ1q+DDc104KFwcTxRMyyP3zfL0A5fNFsUoajVkifPBOi+3rrj2dlrwQJp7bv/WdBrv8R7WXbZLOx3EOZLnFzqmy63Hb2n6rbpAtYuILdAzmL4cW9/sGZCbnCUsBmwh/xk3/wTEUdHHqgLIkjPsvD0Z/AJmSf/ub3rsBG9mIvpDSyB+ok0ymsqda2W3Fe5+8zJ7AikO8W9OwhBoGLOaTBJKxl7ujy+z6BZjt4FaOUtl1StxjVk7j6Pzc0Io8EOronoe+PMJF2AthdtSZglf0CvHaKT43nh+mKmXv8hk2o/APpuSGdH5/0HBxyiziSZZJisEBHAkk8Zyv2SDG7KWyjz3GVpRBbFeRG7zZEbZ8QJSfN2d6eqa7lYEnyyTXZk2irkCLuMS7WJgGybgGPna49sj4/9YoithMPomPIz9Zt2/3SsKX/nc=
    on_success: change
    on_failure: always
