apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kube-queue-job-class: "<%= spec.job_class.name %>"
    kube-queue-job-id: "<%= job.job_id %>"
    kube-queue-job-payload: '<%= payload %>'
  name: "<%= spec.job_name(job.job_id) %>"
  namespace: <%= spec.namespace %>
  labels:
    kube-queue-job: "true"
    kube-queue-worker-name: "<%= spec.worker_name %>"
    kube-queue-job-class: "<%= spec.job_class.name %>"
    kube-queue-job-id: "<%= job.job_id %>"
spec:
  template:
    metadata:
      annotations:
        kube-queue-job-class: "<%= spec.job_class.name %>"
        kube-queue-job-id: "<%= job.job_id %>"
        kube-queue-job-payload: '<%= payload %>'
      labels:
        kube-queue-job: "true"
        kube-queue-worker-name: "<%= spec.worker_name %>"
        kube-queue-job-class: "<%= spec.job_class.name %>"
        kube-queue-job-id: "<%= job.job_id %>"
    spec:
      containers:
      - name: "test-worker"
