default: &default
  adapter: mysql2
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: kube_queue_myapp_development

test:
  <<: *default
  database: kube_queue_myapp_test

production:
  <<: *default
  database: kube_queue_myapp_production
